[tool.poetry]
name = "Kit_Big_Data_To_Do_List"
version = "0.1.0"
description = "To Do List helps you manage your agenda by creating a list of your tasks"
authors = ["Florent Briand <florent.briand56@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.25.2"
altair = "5.1.2"
attrs = "23.1.0"
blinker = "1.6.3"
build = "0.10.0"
cachecontrol = "0.13.1"
cachetools = "5.3.1"
certifi = "2023.7.22"
charset-normalizer = "3.3.0"
cleo = "2.0.1"
click = "8.1.7"
colorama = "0.4.6"
crashtest = "0.4.1"
distlib = "0.3.7"
dulwich = "0.21.6"
filelock = "3.12.4"
gitdb = "4.0.10"
gitpython = "3.1.40"
idna = "3.4"
importlib-metadata = "6.8.0"
installer = "0.7.0"
jaraco-classes = "3.3.0"
jinja2 = "3.1.2"
jsonschema = "4.17.3"
jsonschema-specifications = "2023.7.1"
keyring = "24.2.0"
markdown-it-py = "3.0.0"
markupsafe = "2.1.3"
mdurl = "0.1.2"
more-itertools = "10.1.0"
msgpack = "1.0.7"
packaging = "23.2"
pexpect = "4.8.0"
pillow = "10.1.0"
pkginfo = "1.9.6"
platformdirs = "3.11.0"
poetry = "1.6.1"
poetry-core = "1.7.0"
poetry-plugin-export = "1.5.0"
protobuf = "4.24.4"
ptyprocess = "0.7.0"
pyarrow = "13.0.0"
pydeck = "0.8.1b0"
pygments = "2.16.1"
pyproject-hooks = "1.0.0"
pyrsistent = "0.19.3"
python-dateutil = "2.8.2"
pytz = "2023.3.post1"
pywin32-ctypes = "0.2.2"
rapidfuzz = "2.15.2"
referencing = "0.30.2"
requests = "2.31.0"
requests-toolbelt = "1.0.0"
rich = "13.6.0"
rpds-py = "0.10.6"
shellingham = "1.5.4"
six = "1.16.0"
smmap = "5.0.1"
tenacity = "8.2.3"
toml = "0.10.2"
tomlkit = "0.12.1"
toolz = "0.12.0"
tornado = "6.3.3"
trove-classifiers = "2023.10.18"
typing-extensions = "4.8.0"
tzdata = "2023.3"
tzlocal = "5.1"
urllib3 = "2.0.7"
validators = "0.22.0"
virtualenv = "20.24.6"
watchdog = "3.0.0"
zipp = "3.17.0"
tabulate = "^0.9.0"
streamlit = "^1.28.0"
sphinx = "^7.2.6"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
pydocstyle = "^6.3.0"
pytest-cov = "^4.1.0"
black = "^23.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
